<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.hybridFramework.productDetailsPage.VerifyProductCounts" tests="2" time="0.007" ignored="8" failures="0" timestamp="05 Jul 2019 12:15:26 GMT" skipped="0" hostname="PIL-PC-1048" errors="2">
  <testcase name="afterMethod" time="0.003" classname="com.hybridFramework.productDetailsPage.VerifyProductCounts">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.hybridFramework.testBase.TestBase.getScreenShot(TestBase.java:132)
	at com.hybridFramework.testBase.TestBase.getresult(TestBase.java:166)
	at com.hybridFramework.testBase.TestBase.afterMethod(TestBase.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="testVerifyProductCounts" time="0.004" classname="com.hybridFramework.productDetailsPage.VerifyProductCounts">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.hybridFramework.productDetailsPage.VerifyProductCounts.testVerifyProductCounts(VerifyProductCounts.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testVerifyProductCounts -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
  <testcase name="launchBrowser" classname="com.hybridFramework.testBase.TestBase">
    <skipped/>
  </testcase> <!-- launchBrowser -->
</testsuite> <!-- com.hybridFramework.productDetailsPage.VerifyProductCounts -->
